version: '3.9'

services:
  medical-services.api:
    image: ${DOCKER_REGISTRY-}medicalservicesapi
    build:
      context: .
      dockerfile: src/medical-services.api/Dockerfile
    depends_on:
      - medical-services-db

  medical-services-db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer

volumes:
  pgdata:
