version: '3.9'

services:
  medical-services.api:
    image: ${DOCKER_REGISTRY-}medicalservicesapi
    build:
      context: .
      dockerfile: src/medical-services.api/Dockerfile
    profiles: [dev]
    depends_on:
      - medical-services-db

  medical-services-db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  migrations:
    image: ${DOCKER_REGISTRY-}migrations
    build:
      context: .
      dockerfile: src/migrations/Dockerfile
    profiles: [migration]
    depends_on:
      - medical-services-db

  adminer:
    image: adminer

volumes:
  pgdata:
