// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using datalayer;

namespace migrations.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    partial class MigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ClinicDoctorMedicalProfile", b =>
                {
                    b.Property<long>("MedicalProfilesId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClinicDoctorsClinicId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClinicDoctorsDoctorId")
                        .HasColumnType("bigint");

                    b.HasKey("MedicalProfilesId", "ClinicDoctorsClinicId", "ClinicDoctorsDoctorId");

                    b.HasIndex("ClinicDoctorsClinicId", "ClinicDoctorsDoctorId");

                    b.ToTable("ClinicDoctorMedicalProfile");
                });

            modelBuilder.Entity("DoctorMedicalProfile", b =>
                {
                    b.Property<long>("DoctorsId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicalProfilesId")
                        .HasColumnType("bigint");

                    b.HasKey("DoctorsId", "MedicalProfilesId");

                    b.HasIndex("MedicalProfilesId");

                    b.ToTable("DoctorMedicalProfile");
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.Clinic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinic");
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.ClinicDoctor", b =>
                {
                    b.Property<long>("ClinicId")
                        .HasColumnType("bigint");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.HasKey("ClinicId", "DoctorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("ClinicDoctor");
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.MedicalProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicalProfile");
                });

            modelBuilder.Entity("ClinicDoctorMedicalProfile", b =>
                {
                    b.HasOne("datalayer.abstraction.Entities.MedicalProfile", null)
                        .WithMany()
                        .HasForeignKey("MedicalProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("datalayer.abstraction.Entities.ClinicDoctor", null)
                        .WithMany()
                        .HasForeignKey("ClinicDoctorsClinicId", "ClinicDoctorsDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorMedicalProfile", b =>
                {
                    b.HasOne("datalayer.abstraction.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("datalayer.abstraction.Entities.MedicalProfile", null)
                        .WithMany()
                        .HasForeignKey("MedicalProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.Clinic", b =>
                {
                    b.OwnsOne("datalayer.abstraction.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<long>("ClinicId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int?>("Appartament")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CityCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CountryISO")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("HouseBuilding")
                                .HasColumnType("integer");

                            b1.Property<int>("HouseNnumber")
                                .HasColumnType("integer");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("integer");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ClinicId");

                            b1.HasIndex("CityCode");

                            b1.ToTable("Clinic");

                            b1.WithOwner()
                                .HasForeignKey("ClinicId");
                        });

                    b.OwnsOne("datalayer.abstraction.Entities.MapPoint", "MapPoint", b1 =>
                        {
                            b1.Property<long>("ClinicId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<double>("NorthLatitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("WesternLongitude")
                                .HasColumnType("double precision");

                            b1.HasKey("ClinicId");

                            b1.ToTable("Clinic");

                            b1.WithOwner()
                                .HasForeignKey("ClinicId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("MapPoint");
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.ClinicDoctor", b =>
                {
                    b.HasOne("datalayer.abstraction.Entities.Clinic", "Clinic")
                        .WithMany("DoctorsLink")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("datalayer.abstraction.Entities.Doctor", "Doctor")
                        .WithMany("ClinicsLink")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.Clinic", b =>
                {
                    b.Navigation("DoctorsLink");
                });

            modelBuilder.Entity("datalayer.abstraction.Entities.Doctor", b =>
                {
                    b.Navigation("ClinicsLink");
                });
#pragma warning restore 612, 618
        }
    }
}
